# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React JS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_test_client:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
    - name: Pulling the latest repo code
      uses: actions/checkout@master

    - name: Install Node Dependencies
      run: npm install

    - name: Run ReactJS Tests
      run: npm test -- --coverage --watchAll=false
